// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPc4YIJ0WfIX-doQOnrdb4mysmQdUTH7k',
    appId: '1:236147862578:web:af515a1b66af697871602b',
    messagingSenderId: '236147862578',
    projectId: 'finova-aef9a',
    authDomain: 'finova-aef9a.firebaseapp.com',
    storageBucket: 'finova-aef9a.firebasestorage.app',
    measurementId: 'G-HHFT5RV9W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvey5G0M6l341-FcJko_1pMbDhNBwMBwI',
    appId: '1:236147862578:android:60f46c2b2769000c71602b',
    messagingSenderId: '236147862578',
    projectId: 'finova-aef9a',
    storageBucket: 'finova-aef9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATUSYMjWmtqoCPJXNlWMEKp0h7mVCrFZ4',
    appId: '1:236147862578:ios:1961d8e5ac45025071602b',
    messagingSenderId: '236147862578',
    projectId: 'finova-aef9a',
    storageBucket: 'finova-aef9a.firebasestorage.app',
    iosBundleId: 'com.example.finova',
  );
}
